# Generated by Django 4.0.5 on 2022-07-18 13:17

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docker_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecore',
            name='docker_compose',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1024, verbose_name='Конфиг docker-compose'),
        ),
    ]
